// Generates lib/typert.host.js for @gaowen/dsh-session-notify.
// Mirrors the @deepseek-ai/dsh-typert-generator output shape; the artifact is
// committed, so this script only needs to run when the wire surface changes.
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Render one interface/type body as an escaped single-line declaration string. */
const decl = (body) => JSON.stringify(body)

const manifest = `/* Generated by scripts/gen-typert.mjs — do not edit by hand.
   Mirrors the @deepseek-ai/dsh-typert-generator output shape and is validated
   at load by validateTypertManifest (dsh-typert-loader). */
import { z } from 'zod'

const _sessionId$schema = z.intersection(z.string(), z.unknown())
const _getStateRequest$schema = z.object({})
const _setArmedRequest$schema = z.object({
  'armed': z.boolean(),
})
const _notifyState$schema = z.object({
  'armed': z.boolean(),
})
const _setArmedResult$schema = z.object({
  'armed': z.boolean(),
})
const _previewResult$schema = z.object({
  'ok': z.boolean(),
})

const NOTIFY_DOC = 'Session notification service (\`ctx.sessionNotify\`): the Host half of the completion bell. Remote methods read/write the armed flag for the calling session; the event listeners drive the sound at run completion.'
const NOTIFY_JSDOC = '/**\\n * Session notification service (\`ctx.sessionNotify\`): the Host half of the\\n * completion bell. Remote methods read/write the armed flag for the calling\\n * session; the event listeners drive the sound at run completion.\\n */'

export const TYPERT = {
  package: '@gaowen/dsh-session-notify',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@gaowen/dsh-session-notify#sessionNotify/getState',
      service: 'sessionNotify',
      namespace: 'sessionNotify',
      method: 'getState',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'session',
          wire: 'sessionId',
          source: 'lookup',
          lookup: 'session',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _sessionId$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@gaowen/dsh-session-notify/types#NotifyGetStateRequest',
            schema: _getStateRequest$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@gaowen/dsh-session-notify/types#NotifyState',
        schema: _notifyState$schema,
      },
      sourceLocation: { 'file': 'plugins/dsh-session-notify/packages/session-notify/src/index.ts', 'line': 90, 'column': 9 },
    },
    {
      id: '@gaowen/dsh-session-notify#sessionNotify/setArmed',
      service: 'sessionNotify',
      namespace: 'sessionNotify',
      method: 'setArmed',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'session',
          wire: 'sessionId',
          source: 'lookup',
          lookup: 'session',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _sessionId$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@gaowen/dsh-session-notify/types#NotifySetArmedRequest',
            schema: _setArmedRequest$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@gaowen/dsh-session-notify/types#NotifySetArmedResult',
        schema: _setArmedResult$schema,
      },
      sourceLocation: { 'file': 'plugins/dsh-session-notify/packages/session-notify/src/index.ts', 'line': 98, 'column': 9 },
    },
    {
      id: '@gaowen/dsh-session-notify#sessionNotify/preview',
      service: 'sessionNotify',
      namespace: 'sessionNotify',
      method: 'preview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'session',
          wire: 'sessionId',
          source: 'lookup',
          lookup: 'session',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _sessionId$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@gaowen/dsh-session-notify/types#NotifyGetStateRequest',
            schema: _getStateRequest$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@gaowen/dsh-session-notify/types#NotifyPreviewResult',
        schema: _previewResult$schema,
      },
      sourceLocation: { 'file': 'plugins/dsh-session-notify/packages/session-notify/src/index.ts', 'line': 108, 'column': 9 },
    },
  ],
  model: {
    'services': [
      {
        'description': NOTIFY_DOC,
        'summary': NOTIFY_DOC,
        'tags': [],
        'jsDoc': NOTIFY_JSDOC,
        'key': 'sessionNotify',
        'exportName': 'SessionNotifyService',
        'members': [
          {
            'kind': 'method',
            'name': 'getState',
            'signature': "@Remote('getState') async getState(session: Session): Promise<NotifyState>",
            'summary': 'Current armed state for one session.',
            'jsDoc': '/** Current armed state for one session. */',
          },
          {
            'kind': 'method',
            'name': 'setArmed',
            'signature': "@Remote('setArmed') async setArmed(session: Session, request: NotifySetArmedRequest): Promise<NotifySetArmedResult>",
            'summary': 'Arm or disarm one session.',
            'jsDoc': '/** Arm or disarm one session. */',
          },
          {
            'kind': 'method',
            'name': 'preview',
            'signature': "@Remote('preview') async preview(session: Session, request: NotifyGetStateRequest): Promise<NotifyPreviewResult>",
            'summary': 'Play the configured sound immediately (sound preview / test).',
            'jsDoc': '/** Play the configured sound immediately (sound preview / test). */',
          },
        ],
        'types': [
          {
            'name': 'NotifyGetStateRequest',
            'declaration': ${decl('export interface NotifyGetStateRequest {\n}')},
          },
          {
            'name': 'NotifyMode',
            'declaration': "export type NotifyMode = 'one-shot' | 'sticky';",
          },
          {
            'name': 'NotifyPreviewResult',
            'declaration': ${decl('export interface NotifyPreviewResult {\n    ok: boolean;\n}')},
          },
          {
            'name': 'NotifySetArmedRequest',
            'declaration': ${decl('export interface NotifySetArmedRequest {\n    armed: boolean;\n}')},
          },
          {
            'name': 'NotifySetArmedResult',
            'declaration': ${decl('export interface NotifySetArmedResult {\n    armed: boolean;\n}')},
          },
          {
            'name': 'NotifyState',
            'declaration': ${decl('export interface NotifyState {\n    armed: boolean;\n}')},
          },
        ],
      },
    ],
    'events': [],
    'objects': [],
  },
}

export default TYPERT
`

writeFileSync(join(root, 'lib', 'typert.host.js'), manifest, 'utf8')
